modified:   TileScript.cs~
UNLV-CS472-672/2024-S-GROUP8-CW pull request #6
Opened 2024-02-22 21:43 UTC by GNAR1ZARD

Ive converted the boardXPos and boardYPos variables into properties with private setters, assuming that these values are initialized once and should not be modified externally.

The IsPlayerControlled and IsEnemyControlled properties have been created with both getters and setters. When these properties are set, they call the UpdateTileColor method to update the tile's material color.

The Start method initializes the rendererReference and loads the materials for both the player and enemy. It then calls UpdateTileColor to set the initial color state of the tile.
- note: assumes that the tile materials are located within a Resources folder

The UpdateTileColor method contains a check for an error state where both _isPlayerControlled and _isEnemyControlled are true, it logs an error in this case.

2024-02-22 23:49 UTC, CodingAdam commented
I like the use of encapsulated logic for the enemy/player control bools. With the idea of future applications, this is fine for now but we may want to give players the option of picking colors from a selection of materials. Currently I think it's no issue, just something to kind in mind when hardcoding materials for players. P.S we may want to add more than 2 players in future both to test our capabilities, but also for general multiplayer.

2024-02-23 03:56 UTC, Grimmblood commented
It looks like the changes to how playerColor and enemyColor are loaded produces a compiler error, and the use of defaultColor also produces a compiler error.

It also seems like making the tile's ownership private prevents us from being able to set the ownership prior to game start, and we don't currently have a way to change the tile's ownership via in-game action yet. Perhaps we need to set up a "board controller" that will initialize a tile's ownership.

2024-02-23 03:57 UTC, Grimmblood commented on Crypto Wars/Assets/Scripts/TileScript.cs
> +using UnityEngine;
redundant duplicate?

2024-02-23 03:59 UTC, Grimmblood commented on Crypto Wars/Assets/Scripts/TileScript.cs
> +            rendererReference.material = defaultColor; // Not controlled by anyone
I think we may need to create a material for default color first, which could be done in the unity editor, so probably best to just take this out for now.

2024-02-23 04:09 UTC, Grimmblood requested changes
Never used the code review functionality before, this is neat.

It seems like the enemyColor and playerColor initializers need to be cast, or at least, they were producing compiler errors when I copied those lines into unity.

The defaultColor variable probably needs to have a material created, which can be done through the unity editor, so I don't think it can be done only with code, so we probably just want to temporarily remove the last else block.

Other than that, looks good. We probably need a separate "board controller" that can initialize the colors of the starting tiles, though that is not related to this PR.

2024-02-23 04:09 UTC, Grimmblood commented on Crypto Wars/Assets/Scripts/TileScript.cs
> +        enemyColor = Resources.Load<Material>("Materials/EnemyTileColor");
enemyColor and playerColor need casting, otherwise they produce a compiler error

2024-02-23 04:09 UTC, Grimmblood commented on Crypto Wars/Assets/Scripts/TileScript.cs
> +            rendererReference.material = defaultColor; // Not controlled by anyone
I think we may need to create a material for default color first, which could be done in the unity editor, so probably best to just take this out for now.

2024-02-23 04:22 UTC, CodingAdam commented
Boardcontroller is definitely something we will need to work on for set the initial tiles values and placements. It probably run globally along with the other global functions.

2024-02-28 18:49 UTC, Grimmblood approved these changes

2024-02-29 23:46 UTC, CodingAdam approved these changes

2024-02-29 23:46 UTC, merged